// frontend-next/app/home/page.tsx
import React from "react";
import EmptyState from "../components/EmptyState";
import Map from "./components/map/Map";
import Nearby from "./components/nearby/Nearby";
import getCurrentUser from "@/app/actions/getCurrentUser";
import InteractiveViewer from "./components/nearby/InteractiveViewer";

async function Home() {
  const currentUser = await getCurrentUser();
  return (
    <div className=" h-full flex flex-col lg:flex-row justify-center items-center w-full  lg:px-40 bg-black">
      <InteractiveViewer user={currentUser!} />
    </div>
  );
}

export default Home;

// frontend/components/Home.vue
<template>
  <div
    class="text-white text-lg font-bold font-sans flex flex-col w-full h-screen bg-black items-center justify-center"
  >
    <img src="~/assets/img/logo.png" />
    <n-button>Start experiencing nearby</n-button>
  </div>
</template>

<script>
import { NButton } from "naive-ui";
export default {
  components: {
    NButton,
  },
  setup() {
    return {};
  },
};
</script>

<style lang="scss" scoped></style>
